require: rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    - test/**/*

Layout/LineLength:
  Enabled: true
  Exclude:
    - loco-rails-core.gemspec

Naming/FileName:
  Enabled: true
  Exclude:
    - lib/loco-rails-core.rb

Style/Documentation:
  Enabled: false
